### ISSUE TITLE
Modeling Lockdown

### ISSUE THREAD

**Issue by antoniocaruso** [pcaressa/note-epidemie#1]
Salve,
Molto carino il notebook, complimenti. 

Conosci modelli che fanno dipendere R0 dal tempo (beta/gamma) per modellare un progressivo lockdown?  Sarebbe interessante.

**Comment by pcaressa** [comment]
Grazie.
I modelli che ho approfondito sono in realtà tutti semplici e deterministici, analoghi a quelli che illustro nel foglio: la variabilità dei parametri non li rende più parametri ma nuove variabili del modello, aumentando di una dimensione, e richiedendo di modellizzare la variabile con una nuova equazione... credo che questi modelli vengano fatti girare a ogni aggiornamento dei dati per vedere proprio il trend dei parametri.

Non sarebbe difficile  aggiungere al foglio un programmino che parte da una serie storica diciamo di tre punti e applica la calibrazione, poi fa la stessa cosa aggiungendo un punto, etc. In questo modo otterremmo una serie di valori per beta/gamma (o l'equivalente) e quindi potremmo vederne il trend...

Lo scopo di questo esercizio era un altro, ma comunque lo spunto è interessante, grazie!
P
